using Hwdtech;
using Hwdtech.Ioc;
using Moq;
using SpaceBattle.Lib;

namespace SpaceBattle.Lib.Tests;

public class AutoGeneratedAdapterTests
{
    public AutoGeneratedAdapterTests()
    {
        new InitScopeBasedIoCImplementationCommand().Execute();
        IoC.Resolve<Hwdtech.ICommand>("Scopes.Current.Set", IoC.Resolve<object>("Scopes.New", IoC.Resolve<object>("Scopes.Root"))).Execute();
    }
    [Fact]
    public void MoveCommand_IsAutoResolved_And_ExecutesSuccessfully()
    {
        new InitAdapterGenerationCommand().Execute();
        new InitUniversalDiStrategyCommand().Execute();

        new InitTypesAutoRegistrationCommand(typeof(SpaceBattle.Lib.ICommand), "Commands.", "Command").Execute();

        var objMock = new Mock<IUObject>();
        var startPosition = new Vector(12, 5);
        var velocity = new Vector(-7, 3);
        var expectedPosition = new Vector(5, 8);

        IoC.Resolve<Hwdtech.ICommand>("IoC.Register", "Movable.Position.Get", (object[] args) => startPosition).Execute();
        IoC.Resolve<Hwdtech.ICommand>("IoC.Register", "Movable.Velocity.Get", (object[] args) => velocity).Execute();

        Vector? actualSetPosition = null;
        IoC.Resolve<Hwdtech.ICommand>("IoC.Register", "Movable.Position.Set", (object[] args) =>
        {
            actualSetPosition = (Vector)args[1];
            return new ActionCommand(() => { });
        }).Execute();

        var moveCmd = IoC.Resolve<ICommand>("Commands.Move", objMock.Object);

        moveCmd.Execute();

        Assert.NotNull(moveCmd);
        Assert.IsType<MoveCommand>(moveCmd);
        Assert.Equal(expectedPosition, actualSetPosition);
    }
}


public class ActionCommand : ICommand
{
    private readonly Action _action;
    public ActionCommand(Action action) => _action = action;
    public void Execute() => _action();
}
